apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-test-metrics-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-test-metrics-reader
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: k8s-test-metrics-reader
    spec:
      containers:
        - image: k8s-test-metrics-reader:v1.0.1
          name: k8s-test-metrics-reader
          env:
            - name: TARGET_NAMESPACE
              value: "default"
  serviceAccount: k8s-test-metrics-reader
  serviceAccountName: k8s-test-metrics-reader

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-test-metrics-reader
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-test-metrics-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods","nodes","services",]
    verbs: ["get","list", "watch"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-test-metrics-reader
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods","nodes","services",]
    verbs: ["get","list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-test-metrics-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-test-metrics-reader
subject:
  kind: ServiceAccount
  name: k8s-test-metrics-reader
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-test-metrics-reader
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-test-metrics-reader
subject:
  apiGroup: ""
  kind: ServiceAccount
  name: k8s-test-metrics-reader
  namespace: default